---
version: 2
plan:
  project-key: TES
  key: TES
  name: Visa resultat
stages:
  - Bygg:
    - Build
    - Build2

Build:
  tasks:
    - script:
      - echo 'Hello skidesultat!'
      
Build2:
  tasks:
    - script:
      - echo 'Hello skidesultat!'
